export const CREATE_CELLS_START = "CREATE_CELLS_START";
export const CREATE_CELLS_FINISHED = "CREATE_CELLS_FINISHED";

export const CREATE_RANDOM_GENERATION = "CREATE_RANDOM_GENERATION";
export const CREATE_RANDOM_GENERATION_END = "CREATE_RANDOM_GENERATION_END";

export const TOGGLE_CELL = "TOGGLE_CELL";
export const TOGGLE_CELL_END = "TOGGLE_CELL_END";

export const CREATE_NEXT_GENERATION_START = "CREATE_NEXT_GENERATION_START";
export const CREATE_NEXT_GENERATION_END = "CREATE_NEXT_GENERATION_END";

export const STOP_SIMULATION = "STOP_SIMULATION";
export const START_SIMULATION = "START_SIMULATION";
export const PAUSE_SIMULATION = "PAUSE_SIMULATION";

export const UPDATE_SIMULATION_SPEED = "UPDATE_SIMULATION_SPEED";
export const UPDATE_GRID_SIZE = "UPDATE_GRID_SIZE";
